email:
  delivery_method: smtp
  options:
    address: postfix.biola.edu

redis:
  url: "redis://redis1.prod.biola.edu:6379/0"

trogdir:
  scheme: https
  host: api.biola.edu
  script_name: directory
  version: v1