oracle:
  connection_string: # set in settings.local.yml

redis:
  url: "redis://localhost:6379/0"

schedule:
  hour: 5

sentry:
  url: # Sentry URL set in settings.local.yml

trogdir:
  scheme: http
  host: localhost
  port: 3000
  script_name:
  version: v1
  access_id: # set in settings.local.yml
  secret_key: # set in settings.local.yml
  api_timeout: 300 # 5 min
